# Generated by Django 3.2.8 on 2021-12-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyapp', '0003_auto_20211201_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
