# Generated by Django 3.2.8 on 2021-12-01 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyapp', '0005_auto_20211201_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='name',
        ),
    ]
