# Generated by Django 3.2.8 on 2021-12-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyapp', '0006_remove_hobby_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='name',
            field=models.CharField(default='football', max_length=200),
            preserve_default=False,
        ),
    ]
