# Generated by Django 3.2.8 on 2021-12-01 19:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyapp', '0007_hobby_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='london', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2021, 12, 1, 19, 6, 14, 868413, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
