# Generated by Django 3.2.8 on 2021-12-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyapp', '0008_auto_20211201_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profileImage',
        ),
    ]
