# Generated by Django 3.2.8 on 2021-12-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyapp', '0009_remove_user_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(default='media/default_pic.png', upload_to='profile_pic'),
        ),
    ]
