# Generated by Django 3.2.8 on 2021-12-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyapp', '0010_user_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dateOfBirth',
        ),
    ]
