# Generated by Django 3.2.8 on 2021-12-01 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyapp', '0011_remove_user_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
