# Generated by Django 3.2.8 on 2021-12-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyapp', '0016_auto_20211213_1420'),
        ('hobbyapp', '0022_alter_user_dateofbirth'),
    ]

    operations = [
    ]
